### ISSUE TITLE
Rename basic attacker bots.

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita_template#25]
There are not really attacking anyone.

**Comment by otizonaizit** [comment]
The name is not perfect, but I don't see literally anyone confused by it once they start using pelita and looking at the demos. Do you have a better proposal? If not, close the issue.
You can figure it like in soccer. The attacker goes into the other half of the field to score points, the defender stays in its own half to defend the thing that let the others make points.

**Comment by Debilski** [comment]
I mean, yes, it is not a source of confusion. But when I try to explain our defensive player to people, I tell them it is _attacking_ the other bots, and then when I get to the next demo, I have to say that the ‘attacking’ player is merely a food eating player (well, why not call it that).
The Berkeley Pacman called them _defensive_ and _offensive_ btw. Maybe that makes more sense if we want to keep football terms?
